#!/bin/sh

/bin/busybox --install -s /bin
echo -e "\e[?25l"
clear

# Mount dev, proc, sys
mkdir proc sys
mount -t devtmpfs devtmpfs /dev
mkdir -p dev/pts
mount -t devpts devpts /dev/pts
mount -t proc proc /proc
mount -t sysfs sysfs /sys

echo 0 > /proc/sys/kernel/printk

# Load modules
modprobe sd_mod
modprobe ahci
modprobe crc32c_generic
modprobe loop
modprobe ext4

ROOT=`cat /proc/cmdline |grep -o 'root=[^ ]*'|sed 's/root=//g'`
IMAGE=`cat /proc/cmdline |grep -o 'image=[^ ]*'|sed 's/image=//g'`

mkdir -p images
mount ${ROOT} /images -o discard,noatime
mkdir -p /new_root
mount /images/${IMAGE} /new_root -o nobarrier,discard,noatime
mount --move /images /new_root/boot/images

RESULT=`mount|grep -q new_root;echo $?`

if [ "$RESULT" = "1" ]; then
	modprobe ohci_pci
	modprobe usbhid
	modprobe hid_generic
	exec setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
fi

echo 4 > /proc/sys/kernel/printk
exec switch_root /new_root /sbin/init

