#!/bin/sh

DATA_ROOT="/Qnap/Projects/linux-initramfs-tools"

KERNEL_VERSION="$1"
ROOTFS_INITRD="/tmp/initrd-$$"

if [ "${KERNEL_VERSION}" = "" ]; then
	KERNEL_VERSION=`uname -r`
fi


mkdir -p ${ROOTFS_INITRD}
mount -t tmpfs tmpfs ${ROOTFS_INITRD}

ORIGIN_PWD=$PWD

INCLUDED_MODULES="sd_mod
scsi_mod
ahci
libahci
libata
loop
ext4
mbcache
fscrypto
jbd2
crc16
crc32c_generic"

cd ${ROOTFS_INITRD}

mkdir -p bin
cp -a /bin/busybox bin/
ln -s /bin/busybox bin/sh
cp -a ${DATA_ROOT}/init ./

mkdir -p lib/modules/${KERNEL_VERSION}

for MODULE in ${INCLUDED_MODULES}
do
	find /lib/modules/${KERNEL_VERSION} -name ${MODULE}.ko -exec cp -a {} lib/modules/${KERNEL_VERSION} \;
done

/bin/busybox depmod -a -b ${ROOTFS_INITRD} ${KERNEL_VERSION}

find .|cpio -o -H newc|xz -T 0 --check=crc32 > ${ORIGIN_PWD}/initrd-${KERNEL_VERSION}.img

cd ${ORIGIN_PWD}

umount ${ROOTFS_INITRD}
rm -rf ${ROOTFS_INITRD}

